version: "3"
services:
    web:
        image: springboot
        deploy:
          replicas: 5
          restart_policy:
            condition: on-failure
          resources:
            limits:
              cpus: "0.1"
              memory: 50M
        ports:
            - "8080:8080"
        networks:
            - webnet
            
    db:
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
          POSTGRES_PASSWORD: admin
networks:
   webnet: