spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    tomcat:
      max-active: 10
      max-idle: 10000
      max-wait: 10000
      test-on-borrow: true
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
    
spring.security.authentication.jwt.validity: 604800000
spring.security.authentication.jwt.secret: ILikeTrains

initialDelay: 10000
fixedDelay: 60000

# server:
#  tomcat:
#    accessLog.enabled: true
#    basedir: "${LOG_PATH}/Application"
#    accessLogPattern: "%h %l %u %t \"%r\" %s %b %D"